### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by Initial-heart-1**
Adding an .md suffix to a file is not recommended when the file does not contain any Markdown syntax.
Generic open source licences can generally be represented in ASCII. Therefore, for compatibility, characters not in ASCII should be avoided and plain text should be used when this is sufficient to convey the intended meaning.

Allow edits by maintainers.

### CODE REVIEW

**Comment by allenfrostline** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

It seems to me GitHub recommends either LICENSE or LICENSE.md. Also it's hard to tell whether a general license file is in Markdown syntax or not. Let me know what you think.

**Comment by Initial-heart-1** [comment]
It seems to me that when the content is parsed separately as a text file and a Markdown file, the same content is obtained, indicating that the file does not contain Markdown syntax.



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年10月4日(星期二) 晚上8:02
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [allenfrostline/pyNCMDUMP] Update LICENSE (PR #4)





 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
 
It seems to me GitHub recommends either LICENSE or LICENSE.md. Also it's hard to tell whether a general license file is in Markdown syntax or not. Let me know what you think.

**Comment by Initial-heart-1** [comment]
That's easy to understand, right?Markdown files are displayed in the same way as text files when not using any Markdown syntax. This can easily be demonstrated in practice.
Of course, in practice there may be some differences due to the font and layout settings of the reader.





------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年10月4日(星期二) 晚上8:02
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [allenfrostline/pyNCMDUMP] Update LICENSE (PR #4)





 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
 
It seems to me GitHub recommends either LICENSE or LICENSE.md. Also it's hard to tell whether a general license file is in Markdown syntax or not. Let me know what you think.

**Comment by Initial-heart-1** [comment]
Text files are more compatible than Markdown files, both with human and machines.
Although Markdown files can also be read as a text file, this may be a barrier for some people to read license.（e.g., a user who is unaware that Markdown can be read as a text file may therefore need to look up information in order to read the licence.）
You may not be able to find a Markdown reader on any device, in contrast to the vast majority of the time you can find a text file reader on any device.

**Comment by allenfrostline** [comment]
Got it. If that’s the concern, I wonder if we should just use .txt instead, as bare LICENSE without suffix isn’t recognized as text file either in many cases. For people using common text editors with little to no md experience, this sounds like the most reasonable answer.

**Comment by Initial-heart-1** [comment]
To be honest, I can't figure out why people don't add .txt to their licenses. Maybe it's so that it doesn't interfere with programs that handle .txt files? Anyway, it has now become an accepted standard.




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年10月4日(星期二) 晚上8:46
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [allenfrostline/pyNCMDUMP] Update LICENSE (PR #4)





 
Got it. If that’s the concern, I wonder if we should just use .txt instead, as bare LICENSE without suffix isn’t recognized as text file either in many cases. For people using common text editors with little to no md experience, this sounds like the most reasonable answer.

**Comment by allenfrostline** [comment]
> To be honest, I can't figure out why people don't add .txt to their licenses. Maybe it's so that it doesn't interfere with programs that handle .txt files? Anyway, it has now become an accepted standard.
> […](#)

Cool so we’re on the same page. Can you make another commit to this PR so that LICENSE is changed to LICENCE.txt? I’ll merge the PR after that.

**Comment by Initial-heart-1** [comment]
OK.




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年10月4日(星期二) 晚上9:17
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [allenfrostline/pyNCMDUMP] Update LICENSE (PR #4)





  
To be honest, I can't figure out why people don't add .txt to their licenses. Maybe it's so that it doesn't interfere with programs that handle .txt files? Anyway, it has now become an accepted standard.
 …
  
Cool so we’re on the same page. Can you make another commit to this PR so that LICENSE is changed to LICENCE.txt? I’ll merge the PR after that.

**Pull request merged**
